/*
* 本文件内容不要人为修改，本文件由"python3 Christmas.py Input/MergeCode/LinkModule"生成
* 如果再次运行生成脚本，人为修改的代码将被删除
* 本文件模板请修改Christmas/Template/LinkModule/Config.templ
* 模块Config请修改Code/Module/??/Once.Config
* 组件Config请修改Code/Component/??/Once.Config
* 修改结束后，终端执行"python3 Christmas.py Input/MergeCode/LinkModule"重新生成此文件
*
* The contents of this file should not be modified. This file is generated by "python3 Christmas.py Input/MergeCode/LinkModule"
* If the generation script is run again, the artificially modified code will be deleted
* This file template settings, please modify Christmas/Template/LinkModule/Config.templ
* Module Config settings, please modify Code/Module/??/Once.Config
* Component Config settings, please modify Code/Component/??/Once.Config
* After the modification, execute "python3 Christmas.py Input/MergeCode/LinkModule" in the terminal to regenerate this file.
*/

const Config = Object.freeze({
    "common":{
        "Lang.enable":true,
        "Lang.range":["def","en"],
        "Theme.enable":true,
        "Theme.range":["","dark"],
    },
    "module":{
        _OperWindow:{},
        _OperTrick:{},
        _OperStorage:{},
        _DataFilling:{},
        _OperEvent:{},
        _DataCheck:{},
        _ServeHttp:{"prefix":{
            "":"",
        },},
        _BrokerUI:{},
    },
    "componentUI":{
        _CompTextarea:{},
        _CompImg:{},
        _FunLoad:{},
        _CompSelect:{},
        _BoxCollapse:{},
        _BoxDropdown:{},
        _BoxTabs:{},
        _CompSwitch:{},
        _BoxMotion:{},
        _CompButton:{},
        _FunTranslate:{},
        _CompRadio:{},
        _BoxDialog:{},
        _PackForm:{},
        _BoxPopover:{},
        _BoxGrid:{},
        _BoxFlex:{},
        _CompCheckbox:{},
        _CompInput:{},
        _CompSelectFilter:{},
    },
    "componentAction":{
        _CompTextarea:{},
        _CompImg:{},
        _FunLoad:{},
        _CompSelect:{},
        _BoxCollapse:{},
        _BoxDropdown:{},
        _BoxTabs:{},
        _CompSwitch:{},
        _BoxMotion:{},
        _CompButton:{},
        _FunTranslate:{},
        _CompRadio:{},
        _BoxDialog:{},
        _PackForm:{},
        _BoxPopover:{},
        _BoxGrid:{},
        _BoxFlex:{},
        _CompCheckbox:{},
        _CompInput:{},
        _CompSelectFilter:{},
    },
})
export default Config;